"""create initial tables

Revision ID: 072568cc4f38
Revises: 
Create Date: 2026-08-22 12:11:43.165461

"""
from os import name
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
from asyncpg import transaction

# revision identifiers, used by Alembic.
revision: str = '072568cc4f38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

currency_enum = ENUM('TOMAN', name='currency_type', create_type=False)
transaction_enum = ENUM('expense', 'income', name= 'transaction_type', create_type=False)

def upgrade() -> None:
    ENUM('TOMAN', name='currency_type').create(op.get_bind(), checkfirst=True)
    ENUM('expense', 'income', name='transaction_type').create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('currency',currency_enum , nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('goal > 0', name=op.f('ck_budgets_check_goal_more_than_zero')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budgets_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('category_id', name=op.f('uq_budgets_category_id'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', transaction_enum, nullable=False),
    sa.Column('currency', currency_enum, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=225), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_check_amount_higher_than_zero')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('budgets')
    op.drop_table('categories')
    ENUM(name='currency_type').drop(op.get_bind(), checkfirst=True)
    ENUM(name='transaction_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
