"""create RBAC

Revision ID: aaf42af77100
Revises: c862ae3c91d6
Create Date: 2026-09-14 21:44:03.581617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf42af77100'
down_revision: Union[str, Sequence[str], None] = 'c862ae3c91d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', 'VIEWER', name='household_role_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_household_members_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'household_id', name=op.f('pk_household_members'))
    )
    op.add_column('categories', sa.Column('household_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_categories_name_household_id'), 'categories', ['name', 'household_id'])
    op.create_foreign_key(op.f('fk_categories_household_id_household'), 'categories', 'household', ['household_id'], ['id'], ondelete='CASCADE')
    op.add_column('household', sa.Column('is_personal', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('household_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_transactions_created_by_users'), 'transactions', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_transactions_household_id_household'), 'transactions', 'household', ['household_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_household_id_household'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_transactions_created_by_users'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'created_by')
    op.drop_column('transactions', 'household_id')
    op.drop_column('household', 'is_personal')
    op.drop_constraint(op.f('fk_categories_household_id_household'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('uq_categories_name_household_id'), 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'household_id')
    op.drop_table('household_members')
    # ### end Alembic commands ###
